#!/bin/bash
#SBATCH --job-name=r_2048
#SBATCH --partition=gpuq       
#SBATCH --ntasks=16             
#SBATCH --nodes=16               
#SBATCH --ntasks-per-node=1     
#SBATCH --time=24:00:00         
#SBATCH --output=run_output.log   

module load hdf5
module load cuda10.0/10.0

mpirun -N 16 --map-by ppr:1:node python render_fly_by_cosmo_time.py 